#!/usr/bin/env python3
"""
Code Changelog Tracker
AI가 만든 모든 코드 변경사항을 reviews 폴더에 기록하고 HTML 뷰어로 확인
"""
import os
import json
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any


class CodeChangeLogger:
    """코드 변경사항 로거"""
    
    def __init__(
        self,
        project_name: str,
        user_request: str = "",
        reviews_dir: str = "reviews",
        port: int = 4000
    ):
        """
        Args:
            project_name: 프로젝트 이름
            user_request: 사용자 요구사항
            reviews_dir: 문서 저장 디렉토리
            port: HTTP 서버 포트
        """
        self.project_name = project_name
        self.user_request = user_request
        self.reviews_dir = Path(reviews_dir)
        self.port = port
        
        # 타임스탬프
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # 변경사항 목록
        self.changes: List[Dict[str, Any]] = []
        
        # reviews 디렉토리 생성
        self.reviews_dir.mkdir(exist_ok=True)
        
        # README.md 초기화 (없으면)
        self._init_readme()
    
    def _init_readme(self):
        """README.md 초기화"""
        readme_path = self.reviews_dir / "README.md"
        if not readme_path.exists():
            content = f"""# {self.project_name} - 코드 변경 이력

이 문서는 AI가 생성한 모든 코드 변경사항을 기록합니다.

## 📋 문서 목록

최신 변경사항부터 확인하세요.

---

Generated by Code Changelog Tracker
"""
            readme_path.write_text(content, encoding='utf-8')
    
    def log_file_creation(
        self,
        file_path: str,
        content: str,
        reason: str
    ):
        """파일 생성 기록"""
        self.changes.append({
            'type': 'creation',
            'file_path': file_path,
            'content': content,
            'reason': reason
        })
    
    def log_file_modification(
        self,
        file_path: str,
        old_content: str,
        new_content: str,
        reason: str
    ):
        """파일 수정 기록"""
        self.changes.append({
            'type': 'modification',
            'file_path': file_path,
            'old_content': old_content,
            'new_content': new_content,
            'reason': reason
        })
    
    def log_file_deletion(
        self,
        file_path: str,
        content: str,
        reason: str
    ):
        """파일 삭제 기록"""
        self.changes.append({
            'type': 'deletion',
            'file_path': file_path,
            'content': content,
            'reason': reason
        })
    
    def log_bug_fix(
        self,
        file_path: str,
        old_content: str,
        new_content: str,
        bug_desc: str,
        fix_desc: str
    ):
        """버그 수정 기록"""
        self.changes.append({
            'type': 'bug_fix',
            'file_path': file_path,
            'old_content': old_content,
            'new_content': new_content,
            'bug_desc': bug_desc,
            'fix_desc': fix_desc
        })
    
    def log_refactoring(
        self,
        file_path: str,
        old_content: str,
        new_content: str,
        refactor_type: str,
        reason: str
    ):
        """리팩토링 기록"""
        self.changes.append({
            'type': 'refactoring',
            'file_path': file_path,
            'old_content': old_content,
            'new_content': new_content,
            'refactor_type': refactor_type,
            'reason': reason
        })
    
    def _generate_markdown(self) -> str:
        """Markdown 문서 생성"""
        lines = []
        
        # 헤더
        lines.append(f"# {self.project_name}")
        lines.append("")
        lines.append(f"**작성 시간**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")
        
        if self.user_request:
            lines.append(f"**요구사항**: {self.user_request}")
            lines.append("")
        
        lines.append("---")
        lines.append("")
        
        # 변경사항 목록
        for i, change in enumerate(self.changes, 1):
            change_type = change['type']
            file_path = change['file_path']
            
            lines.append(f"## {i}. {file_path}")
            lines.append("")
            
            if change_type == 'creation':
                lines.append("**변경 유형**: 파일 생성 ✨")
                lines.append("")
                lines.append(f"**이유**: {change['reason']}")
                lines.append("")
                lines.append("**내용**:")
                lines.append("```")
                lines.append(change['content'])
                lines.append("```")
                lines.append("")
            
            elif change_type == 'modification':
                lines.append("**변경 유형**: 파일 수정 ✏️")
                lines.append("")
                lines.append(f"**이유**: {change['reason']}")
                lines.append("")
                lines.append("**변경 전**:")
                lines.append("```")
                lines.append(change['old_content'])
                lines.append("```")
                lines.append("")
                lines.append("**변경 후**:")
                lines.append("```")
                lines.append(change['new_content'])
                lines.append("```")
                lines.append("")
            
            elif change_type == 'deletion':
                lines.append("**변경 유형**: 파일 삭제 🗑️")
                lines.append("")
                lines.append(f"**이유**: {change['reason']}")
                lines.append("")
                lines.append("**삭제된 내용**:")
                lines.append("```")
                lines.append(change['content'])
                lines.append("```")
                lines.append("")
            
            elif change_type == 'bug_fix':
                lines.append("**변경 유형**: 버그 수정 🐛")
                lines.append("")
                lines.append(f"**버그 설명**: {change['bug_desc']}")
                lines.append(f"**수정 내용**: {change['fix_desc']}")
                lines.append("")
                lines.append("**변경 전**:")
                lines.append("```")
                lines.append(change['old_content'])
                lines.append("```")
                lines.append("")
                lines.append("**변경 후**:")
                lines.append("```")
                lines.append(change['new_content'])
                lines.append("```")
                lines.append("")
            
            elif change_type == 'refactoring':
                lines.append("**변경 유형**: 리팩토링 ♻️")
                lines.append("")
                lines.append(f"**리팩토링 유형**: {change['refactor_type']}")
                lines.append(f"**이유**: {change['reason']}")
                lines.append("")
                lines.append("**변경 전**:")
                lines.append("```")
                lines.append(change['old_content'])
                lines.append("```")
                lines.append("")
                lines.append("**변경 후**:")
                lines.append("```")
                lines.append(change['new_content'])
                lines.append("```")
                lines.append("")
            
            lines.append("---")
            lines.append("")
        
        # 푸터
        lines.append(f"**총 변경사항**: {len(self.changes)}개")
        lines.append("")
        
        return "\n".join(lines)
    
    def save_review(self) -> Path:
        """리뷰 문서 저장"""
        if not self.changes:
            print("⚠️  기록된 변경사항이 없습니다.")
            return None
        
        # Markdown 생성
        markdown = self._generate_markdown()
        
        # 파일 저장
        file_path = self.reviews_dir / f"{self.timestamp}.md"
        file_path.write_text(markdown, encoding='utf-8')
        
        print(f"✓ 변경 이력 저장: {file_path}")
        return file_path
    
    def update_summary(self):
        """SUMMARY.md 업데이트"""
        summary_path = self.reviews_dir / "SUMMARY.md"
        
        # 모든 MD 파일 찾기 (README, SUMMARY 제외)
        md_files = sorted(
            [f for f in self.reviews_dir.glob("*.md") 
             if f.name not in ["README.md", "SUMMARY.md"]],
            reverse=True  # 최신순
        )
        
        lines = [
            "# Summary",
            "",
            "* [홈](README.md)",
            ""
        ]
        
        for md_file in md_files:
            # 타임스탬프를 읽기 좋은 형식으로
            timestamp = md_file.stem
            try:
                dt = datetime.strptime(timestamp, "%Y%m%d_%H%M%S")
                display_name = dt.strftime("%Y-%m-%d %H:%M:%S")
            except:
                display_name = timestamp
            
            lines.append(f"* [{display_name}]({md_file.name})")
        
        summary_path.write_text("\n".join(lines), encoding='utf-8')
        print(f"✓ SUMMARY.md 업데이트: {len(md_files)}개 문서")
    
    def update_index_html(self):
        """index.html 업데이트"""
        index_path = self.reviews_dir / "index.html"
        
        # 모든 MD 파일 찾기 (README, SUMMARY 제외)
        md_files = sorted(
            [f for f in self.reviews_dir.glob("*.md") 
             if f.name not in ["README.md", "SUMMARY.md"]],
            reverse=True  # 최신순
        )
        
        # 파일 목록 생성
        file_list_items = []
        for i, md_file in enumerate(md_files):
            timestamp = md_file.stem
            try:
                dt = datetime.strptime(timestamp, "%Y%m%d_%H%M%S")
                display_name = dt.strftime("%Y-%m-%d %H:%M:%S")
            except:
                display_name = timestamp
            
            active_class = " class='active'" if i == 0 else ""
            file_list_items.append(
                f"        <li{active_class}><a href='#{md_file.name}'>{display_name}</a></li>"
            )
        
        file_list_html = "\n".join(file_list_items)
        
        # 기본 파일 (최신 파일)
        default_file = md_files[0].name if md_files else "README.md"
        
        # HTML 템플릿
        html_content = f"""<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.project_name} - 코드 변경 이력</title>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
            background: #0d1117;
            color: #c9d1d9;
            display: flex;
            height: 100vh;
        }}
        
        .sidebar {{
            width: 280px;
            background: #161b22;
            border-right: 1px solid #30363d;
            overflow-y: auto;
            padding: 20px;
        }}
        
        .sidebar h2 {{
            color: #58a6ff;
            font-size: 18px;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 1px solid #30363d;
        }}
        
        .sidebar ul {{
            list-style: none;
        }}
        
        .sidebar li {{
            margin: 5px 0;
        }}
        
        .sidebar a {{
            color: #8b949e;
            text-decoration: none;
            display: block;
            padding: 8px 12px;
            border-radius: 6px;
            transition: all 0.2s;
            font-size: 14px;
        }}
        
        .sidebar a:hover {{
            background: #21262d;
            color: #58a6ff;
        }}
        
        .sidebar li.active a {{
            background: #1f6feb;
            color: #fff;
        }}
        
        .content {{
            flex: 1;
            overflow-y: auto;
            padding: 40px;
        }}
        
        .markdown-body {{
            max-width: 980px;
            margin: 0 auto;
        }}
        
        .markdown-body h1 {{
            color: #c9d1d9;
            border-bottom: 1px solid #21262d;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }}
        
        .markdown-body h2 {{
            color: #58a6ff;
            margin-top: 30px;
            margin-bottom: 15px;
        }}
        
        .markdown-body h3 {{
            color: #8b949e;
            margin-top: 20px;
            margin-bottom: 10px;
        }}
        
        .markdown-body p {{
            line-height: 1.6;
            margin-bottom: 15px;
        }}
        
        .markdown-body code {{
            background: #161b22;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 85%;
            color: #f0883e;
        }}
        
        .markdown-body pre {{
            background: #161b22;
            padding: 16px;
            border-radius: 6px;
            overflow-x: auto;
            margin: 15px 0;
            border: 1px solid #30363d;
        }}
        
        .markdown-body pre code {{
            background: none;
            padding: 0;
            color: #c9d1d9;
        }}
        
        .markdown-body hr {{
            border: none;
            border-top: 1px solid #21262d;
            margin: 30px 0;
        }}
        
        .markdown-body strong {{
            color: #fff;
        }}
        
        .markdown-body ul {{
            margin-left: 20px;
            margin-bottom: 15px;
        }}
        
        .markdown-body li {{
            margin: 5px 0;
        }}
        
        .loading {{
            text-align: center;
            padding: 50px;
            color: #8b949e;
        }}
    </style>
</head>
<body>
    <div class="sidebar">
        <h2>📋 변경 이력</h2>
        <ul id="file-list">
{file_list_html}
        </ul>
    </div>
    
    <div class="content">
        <div id="markdown-content" class="markdown-body">
            <div class="loading">문서 로딩 중...</div>
        </div>
    </div>
    
    <script>
        const contentDiv = document.getElementById('markdown-content');
        const fileList = document.getElementById('file-list');
        
        // Markdown 파일 로드 및 렌더링
        async function loadMarkdown(filename) {{
            try {{
                const response = await fetch(filename);
                const markdown = await response.text();
                contentDiv.innerHTML = marked.parse(markdown);
                
                // 활성 링크 업데이트
                fileList.querySelectorAll('li').forEach(li => li.classList.remove('active'));
                const activeLink = fileList.querySelector(`a[href="#${{filename}}"]`);
                if (activeLink) {{
                    activeLink.parentElement.classList.add('active');
                }}
                
                // URL 업데이트
                window.location.hash = filename;
            }} catch (error) {{
                contentDiv.innerHTML = '<div class="loading">❌ 파일을 불러올 수 없습니다.</div>';
            }}
        }}
        
        // 링크 클릭 이벤트
        fileList.addEventListener('click', (e) => {{
            if (e.target.tagName === 'A') {{
                e.preventDefault();
                const filename = e.target.getAttribute('href').substring(1);
                loadMarkdown(filename);
            }}
        }});
        
        // 초기 로드 (URL 해시 또는 기본 파일)
        const initialFile = window.location.hash.substring(1) || '{default_file}';
        loadMarkdown(initialFile);
    </script>
</body>
</html>
"""
        
        index_path.write_text(html_content, encoding='utf-8')
        print(f"✓ index.html 업데이트: {len(md_files)}개 문서")
    
    def save_and_build(self) -> Path:
        """저장 + SUMMARY 업데이트 + index.html 업데이트"""
        file_path = self.save_review()
        if file_path:
            self.update_summary()
            self.update_index_html()
        return file_path
    
    def serve_docs(self):
        """문서 서버 실행"""
        print(f"\n🌐 문서 서버 실행 중...")
        print(f"   URL: http://localhost:{self.port}")
        print(f"   종료: Ctrl+C\n")
        
        try:
            subprocess.run(
                ["python3", "-m", "http.server", str(self.port)],
                cwd=self.reviews_dir
            )
        except KeyboardInterrupt:
            print("\n✓ 서버 종료")


def main():
    """명령줄 인터페이스"""
    import sys
    
    if len(sys.argv) < 2:
        print("사용법:")
        print("  python code_changelog_tracker.py init     # 초기화")
        print("  python code_changelog_tracker.py build    # SUMMARY + index.html 업데이트")
        print("  python code_changelog_tracker.py serve    # 문서 서버 실행")
        return
    
    command = sys.argv[1]
    
    logger = CodeChangeLogger("Project")
    
    if command == "init":
        print("✓ reviews 디렉토리 초기화 완료")
    
    elif command == "build":
        logger.update_summary()
        logger.update_index_html()
        print("✓ 빌드 완료")
    
    elif command == "serve":
        port = int(sys.argv[2]) if len(sys.argv) > 2 else 4000
        logger.port = port
        logger.serve_docs()
    
    else:
        print(f"❌ 알 수 없는 명령: {command}")


if __name__ == "__main__":
    main()

